'use strict';
const $ = id => document.getElementById(id);
const art = {
  plate: '<svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="56" fill="#eeeade" stroke="#c5bc9d" stroke-width="2"/><circle cx="60" cy="60" r="51" fill="#fffdf4" stroke="#b5a675"/><circle cx="60" cy="60" r="39" fill="#f0ede3" stroke="#d6ceba"/><circle cx="60" cy="60" r="35" fill="#faf8f0"/></svg>',
  glass: '<svg viewBox="0 0 70 120" aria-hidden="true"><ellipse cx="35" cy="108" rx="24" ry="7" fill="#dbe5dc" fill-opacity=".7" stroke="#85998f"/><path d="M35 64v42" stroke="#e9f1e7" stroke-width="6"/><path d="M35 64v42" stroke="#83958b" stroke-width="1"/><path d="M13 10h44l-3 37c-2 23-36 23-38 0Z" fill="#eaf3e8" fill-opacity=".5" stroke="#83958b" stroke-width="2"/><ellipse cx="35" cy="10" rx="22" ry="6" fill="#ffffff" fill-opacity=".35" stroke="#83958b"/><path d="M21 19l2 27q1 10 9 12" fill="none" stroke="#fff" stroke-width="3"/></svg>',
  fork: '<svg viewBox="0 0 32 140" aria-hidden="true"><path d="M5 4v29q0 13 8 14l-3 82q0 8 6 8t6-8l-3-82q8-1 8-14V4h-4v27h-3V4h-3v27h-3V4h-3v27H9V4Z" fill="#c7ceca" stroke="#808e88"/><path d="M15 53l-1 72" stroke="#fff" stroke-width="2"/></svg>',
  knife: '<svg viewBox="0 0 32 140" aria-hidden="true"><path d="M23 3Q6 14 6 60q0 8 11 8l-5 61q0 8 7 8t7-8L25 4Z" fill="#c7ceca" stroke="#808e88"/><path d="M21 74l-2 53M21 12v46" stroke="#fff" stroke-width="2"/></svg>'
};
const dimensions = {plate:[.28,1],glass:[.15,120/70],fork:[.09,140/32],knife:[.09,140/32]};
let items = [], selected = null, serial = 0, history = [], photoURL = null, photoRequest = 0;
let pointers = new Map(), gesture = null;
const stage = $('stage');
const clamp = (v,a,b) => Math.max(a,Math.min(b,v));
const angle = v => ((v+180)%360+360)%360-180;
const current = () => items.find(i=>i.id===selected);
function checkpoint(){history.push(JSON.stringify({items,selected}));if(history.length>40)history.shift();$('undo').disabled=false;}
function announce(message){$('status').textContent=message;}
function controls(){const item=current();$('selection-label').textContent=item ? `${item.type[0].toUpperCase()+item.type.slice(1)} selected` : 'Select a piece to adjust';$('count').textContent=`${items.length} ${items.length===1?'piece':'pieces'}`;for(const id of ['size','rotation','duplicate','delete'])$(id).disabled=!item;$('size').value=item?.scale??1;$('rotation').value=item?.rotation??0;$('size-value').value=`${Math.round((item?.scale??1)*100)}%`;$('rotation-value').value=`${Math.round(item?.rotation??0)}°`;$('undo').disabled=!history.length;}
function position(el,item){const [width,ratio]=dimensions[item.type];el.style.width=`${width*100}%`;el.style.height=`${stage.clientWidth*width*ratio}px`;el.style.left=`${item.x*100}%`;el.style.top=`${item.y*100}%`;el.style.transform=`translate(-50%,-50%) rotate(${item.rotation}deg) scale(${item.scale})`;el.classList.toggle('selected',item.id===selected);el.setAttribute('aria-pressed',String(item.id===selected));}
function render(){const layer=$('items');layer.replaceChildren();for(const item of items){const el=document.createElement('button');el.className='piece';el.dataset.id=item.id;el.setAttribute('aria-label',`${item.type} ${item.id}`);el.innerHTML=art[item.type];position(el,item);layer.append(el);} $('empty').hidden=!!photoURL||items.length>0;controls();}
function paint(){for(const item of items){const el=$('items').querySelector(`[data-id="${item.id}"]`);if(el)position(el,item);}controls();}
for(const type of Object.keys(art)){const button=document.createElement('button');button.className='product';button.dataset.type=type;button.setAttribute('aria-label',`Add ${type}`);button.innerHTML=`${art[type]}<span>${type[0].toUpperCase()+type.slice(1)}</span>`;button.addEventListener('click',()=>{checkpoint();selected=++serial;items.push({id:selected,type,x:.5+(items.length%3-1)*.06,y:.5,scale:1,rotation:0});render();announce(`${type} added.`);});$('products').append(button);}
function point(e){const rect=stage.getBoundingClientRect();return {x:e.clientX-rect.left,y:e.clientY-rect.top};}
function baseline(){const item=current();if(!item||!pointers.size){gesture=null;return;}const p=[...pointers.values()];gesture={item:{...item},points:p.map(v=>({...v})),width:stage.clientWidth,height:stage.clientHeight};}
stage.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;const target=e.target.closest('.piece');if(!pointers.size){selected=target?Number(target.dataset.id):null;paint();if(!current())return;checkpoint();}if(pointers.size>=2)return;e.preventDefault();stage.focus({preventScroll:true});stage.setPointerCapture(e.pointerId);pointers.set(e.pointerId,point(e));baseline();});
stage.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!gesture)return;e.preventDefault();pointers.set(e.pointerId,point(e));const item=current();if(!item)return;const p=[...pointers.values()], b=gesture.points, original=gesture.item;let dx=p[0].x-b[0].x,dy=p[0].y-b[0].y;if(p.length===2&&b.length===2){const mid=a=>({x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2});const a=mid(b),c=mid(p);const distance=a=>Math.hypot(a[1].x-a[0].x,a[1].y-a[0].y);const direction=a=>Math.atan2(a[1].y-a[0].y,a[1].x-a[0].x);const factor=distance(p)/Math.max(1,distance(b));item.scale=clamp(original.scale*factor,.35,3);const delta=direction(p)-direction(b);item.rotation=angle(original.rotation+delta*180/Math.PI);const effective=item.scale/original.scale;const ox=original.x*gesture.width-a.x,oy=original.y*gesture.height-a.y;dx=c.x+effective*(ox*Math.cos(delta)-oy*Math.sin(delta))-original.x*gesture.width;dy=c.y+effective*(ox*Math.sin(delta)+oy*Math.cos(delta))-original.y*gesture.height;}item.x=clamp(original.x+dx/gesture.width,.03,.97);item.y=clamp(original.y+dy/gesture.height,.03,.97);paint();});
function endPointer(e){if(!pointers.has(e.pointerId))return;pointers.delete(e.pointerId);baseline();}
for(const event of ['pointerup','pointercancel','lostpointercapture'])stage.addEventListener(event,endPointer);
// Keyboard activation also selects pieces, independently of touch pointer events.
$('items').addEventListener('click',e=>{const el=e.target.closest('.piece');if(el){selected=Number(el.dataset.id);paint();}});
for(const id of ['size','rotation']){let started=false;const input=$(id);input.addEventListener('input',()=>{const item=current();if(!item)return;if(!started){checkpoint();started=true;}item[id==='size'?'scale':'rotation']=Number(input.value);paint();});input.addEventListener('change',()=>{started=false;});input.addEventListener('blur',()=>{started=false;});}
$('duplicate').addEventListener('click',()=>{const item=current();if(!item)return;checkpoint();const copy={...item,id:++serial,x:clamp(item.x+.05,.03,.97),y:clamp(item.y+.05,.03,.97)};items.push(copy);selected=copy.id;render();announce('Piece duplicated.');});
function remove(){if(!current())return;checkpoint();items=items.filter(i=>i.id!==selected);selected=null;render();announce('Piece deleted.');}
$('delete').addEventListener('click',remove);
$('undo').addEventListener('click',()=>{if(!history.length)return;({items,selected}=JSON.parse(history.pop()));render();announce('Last arrangement change undone.');});
stage.addEventListener('keydown',e=>{const item=current();if(!item)return;if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove();}const delta={ArrowLeft:[-.01,0],ArrowRight:[.01,0],ArrowUp:[0,-.01],ArrowDown:[0,.01]}[e.key];if(delta){e.preventDefault();checkpoint();item.x=clamp(item.x+delta[0],.03,.97);item.y=clamp(item.y+delta[1],.03,.97);paint();}});
$('choose').addEventListener('click',()=>$('photo-input').click());$('camera').addEventListener('click',()=>$('camera-input').click());
async function loadPhoto(file){if(!file)return;const request=++photoRequest;if(!file.type.startsWith('image/')&&!/\.(heic|heif|jpg|jpeg|png|webp|avif)$/i.test(file.name)){announce('Please choose an image file.');return;}if(file.size>40*1024*1024){announce('This photo is too large. Choose one under 40 MB.');return;}const url=URL.createObjectURL(file);const probe=new Image();try{await new Promise((resolve,reject)=>{probe.onload=resolve;probe.onerror=reject;probe.src=url;});if(request!==photoRequest){URL.revokeObjectURL(url);return;}if(photoURL)URL.revokeObjectURL(photoURL);photoURL=url;$('table-photo').src=url;$('table-photo').hidden=false;stage.style.aspectRatio=`${probe.naturalWidth} / ${probe.naturalHeight}`;$('scene-label').textContent='YOUR TABLE';$('clear-photo').disabled=false;render();announce('Photo ready. Tap a piece below to add it.');}catch{URL.revokeObjectURL(url);if(request===photoRequest)announce('This image could not be opened. Try a JPEG or PNG, or take a new photo.');}}
for(const id of ['photo-input','camera-input'])$(id).addEventListener('change',e=>{loadPhoto(e.target.files[0]);e.target.value='';});
$('clear-photo').addEventListener('click',()=>{++photoRequest;if(photoURL)URL.revokeObjectURL(photoURL);photoURL=null;$('table-photo').removeAttribute('src');$('table-photo').hidden=true;stage.style.aspectRatio='4 / 3';$('scene-label').textContent='YOUR CANVAS';$('clear-photo').disabled=true;render();announce('Photo removed.');});
new ResizeObserver(()=>{pointers.clear();gesture=null;paint();}).observe(stage);
render();
