// Extended deployed-site audit. Synthetic fixtures only. Baseline mode records failures;
// normal mode gates deployment on their regression checks.
const assert=require('node:assert/strict'),fs=require('node:fs'),{webkit}=require('playwright');
(async()=>{
 const base=(process.env.BASE_URL||'http://127.0.0.1:8000/').replace(/\/$/,'')+'/',baseline=process.env.AUDIT_BASELINE==='1';
 const browser=await webkit.launch({headless:true}),report={base,baseline,commit:process.env.GITHUB_SHA||null,checkedAt:new Date().toISOString(),checks:[],performance:{},network:[],console:[],errors:[]};
 fs.mkdirSync('test-results',{recursive:true});
 const check=(id,pass,detail)=>{report.checks.push({id,pass,detail});console.log('AUDIT '+id+' '+(pass?'PASS':'FAIL')+' '+JSON.stringify(detail??''));};
 try{
 const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});await ctx.addInitScript(()=>{window.auditURLs=new Set();const create=URL.createObjectURL,revoke=URL.revokeObjectURL;URL.createObjectURL=function(b){const u=create.call(this,b);window.auditURLs.add(u);return u};URL.revokeObjectURL=function(u){window.auditURLs.delete(u);return revoke.call(this,u)}});const page=await ctx.newPage();page.setDefaultTimeout(20000);
 page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(['error','warning'].includes(m.type()))report.console.push({type:m.type(),text:m.text()})});
 page.on('request',r=>{report.network.push({method:r.method(),url:r.url(),bytes:r.postDataBuffer()?.length||0});});
 const tap=id=>page.locator('#'+id).tap(),state=()=>page.evaluate(()=>structuredClone(scene())),ready=()=>page.waitForFunction(()=>!document.querySelector('main').inert),drawn=()=>page.waitForFunction(()=>renderer3D&&renderer3D.stats().items===items.length&&document.getElementById('table-3d').dataset.stats&&JSON.parse(document.getElementById('table-3d').dataset.stats).items===items.length);
 await page.goto(base);await ready();check('lazy-load',await page.locator('script[src*="dist/table3d"]').count()===0);
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=1200;c.height=800;const d=c.getContext('2d');d.fillStyle='#cbb795';d.fillRect(0,0,c.width,c.height);return c.toDataURL().split(',')[1]});
 const file={name:'audit-synthetic.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')};
 const chooser=page.waitForEvent('filechooser');await tap('choose');await(await chooser).setFiles(file);await page.waitForFunction(()=>is3D());await drawn();
 const contrast=await page.locator('.privacy').evaluate(e=>{const values=s=>s.match(/[\d.]+/g).slice(0,3).map(Number),lum=a=>a.map(n=>n/255).map(n=>n<=.04045?n/12.92:((n+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0),a=lum(values(getComputedStyle(e).color)),b=lum(values(getComputedStyle(document.documentElement).backgroundColor));return (Math.max(a,b)+.05)/(Math.min(a,b)+.05)});check('small-text-contrast',contrast>=4.5,{ratio:contrast});
 check('3d-initializes',await page.locator('#render-status').getAttribute('data-mode')==='3d');
 report.performance.initialLoading=await page.evaluate(()=>({navigation:performance.getEntriesByType('navigation').map(n=>({domContentLoadedMs:n.domContentLoadedEventEnd,loadMs:n.loadEventEnd})),renderer:performance.getEntriesByType('resource').filter(e=>e.name.includes('dist/table3d')).map(e=>({durationMs:e.duration,transferSize:e.transferSize,decodedBytes:e.decodedBodySize}))}));
 const cameraChooser=page.waitForEvent('filechooser');await tap('camera');await(await cameraChooser).setFiles(file);await page.waitForFunction(()=>!!photoBlob);check('capture-routing',await page.locator('#camera-input').getAttribute('capture')==='environment','Synthetic file via camera input; OS camera not simulated');
 const q=[{x:.08,y:.92},{x:.93,y:.85},{x:.67,y:.14},{x:.36,y:.18}];await tap('edit-calibrate');
 for(let i=0;i<4;i++){const h=await page.locator('.corner').nth(i).boundingBox(),r=await page.locator('#stage').boundingBox();await page.mouse.move(h.x+h.width/2,h.y+h.height/2);await page.mouse.down();await page.mouse.move(r.x+q[i].x*r.width,r.y+q[i].y*r.height,{steps:5});await page.mouse.up();}await tap('calibration-done');
 check('calibration-status',/Matched/.test(await page.locator('#render-status').textContent()),await page.locator('#render-status').textContent());
 for(const n of [2,4,6]){await page.locator('#edit-guests').selectOption(String(n));await drawn();check('meshes-'+n,await page.evaluate(()=>renderer3D.stats().items===guestCount*4&&renderer3D.stats().groups===guestCount));}
 await tap('expand');await drawn();
 // Selecting, without moving, must not consume history capacity or hide the preceding edit.
 const historyBefore=await page.evaluate(()=>history.length);await page.locator('.piece[aria-label^="plate"]').nth(2).tap();check('selection-is-not-edit',await page.evaluate(()=>history.length)===historyBefore);
 await page.locator('#size').press('End');await tap('edit-fit');await drawn();check('enlarge-fit',await page.evaluate(()=>TableFit.inside(items,fitContext())));
 const pinch=await page.evaluate(()=>{const before=structuredClone(members()),r=stage.getBoundingClientRect(),target=document.querySelector('.piece.selected'),p=before.find(i=>i.type==='plate'),h=TablePerspective.matrix(calibration),original=stage.setPointerCapture;stage.setPointerCapture=()=>{};const emit=(type,id,x,y,node=stage)=>{const v=TablePerspective.project(h,{x,y});node.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,pointerType:'touch',pointerId:id,clientX:r.x+v.x*r.width,clientY:r.y+v.y*r.height}))};emit('pointerdown',701,p.x,p.y,target);emit('pointerdown',702,p.x+.07,p.y);emit('pointermove',702,p.x+.075,p.y+.015);emit('pointerup',702,p.x+.075,p.y+.015);emit('pointerup',701,p.x,p.y);stage.setPointerCapture=original;return {before,after:structuredClone(members()),ratio:planeRatio(),pointers:pointers.size}});const dist=(a,b)=>Math.hypot(a.x-b.x,(a.y-b.y)/pinch.ratio),pf=pinch.after[0].scale/pinch.before[0].scale;check('3d-pinch-group-geometry',pinch.pointers===0&&pinch.after.length===4&&pinch.after.slice(1).every((p,i)=>Math.abs(dist(pinch.after[0],p)-dist(pinch.before[0],pinch.before[i+1])*pf)<1e-7));await tap('edit-fit');
 await tap('tool-spacing');for(const mode of ['compact','formal','standard']){await tap('spacing-'+mode);await drawn();check('spacing-'+mode,await page.evaluate(m=>currentGroup().spacing===m,mode));}await tap('tool-size');
 const forwardBefore=await state(),forwardGroup=await page.evaluate(()=>current().groupId);await tap('forward');check('3d-bring-forward',((await state()).items.at(-1).groupId===forwardGroup));await tap('undo');check('3d-front-undo',JSON.stringify(await state())===JSON.stringify(forwardBefore));
 const keyboardBefore=await state();await page.locator('#stage').press('ArrowRight');check('keyboard-moves-selection',JSON.stringify((await state()).items)!==JSON.stringify(keyboardBefore.items));await tap('undo');check('keyboard-undo',JSON.stringify((await state()).items)===JSON.stringify(keyboardBefore.items));
 const unnamed=await page.locator('button,select,input[type=range]').evaluateAll(es=>es.filter(e=>e.getClientRects().length&&!e.getAttribute('aria-label')&&!e.textContent.trim()&&!e.labels?.length).map(e=>e.id));check('controls-labelled',unnamed.length===0,unnamed);
 // Instrument a public renderer lifecycle method, not an implementation-shaped mock.
 const redundant=await page.evaluate(()=>{let calls=0;const solve=TableCamera.solve;TableCamera.solve=(...a)=>{calls++;return solve(...a)};renderer3D.suspend(false);TableCamera.solve=solve;return calls});check('resume-is-idempotent',redundant===0,{cameraSolves:redundant});
 await tap('tab-save');await page.locator('#performance summary').tap();await tap('perf-start');await tap('tab-arrange');await tap('render-mode');await tap('tab-save');await page.waitForTimeout(150);
 check('benchmark-cancels-on-2d',!/Measuring/.test(await page.locator('#perf-output').textContent()),await page.locator('#perf-output').textContent());await tap('tab-arrange');await tap('render-mode');await drawn();
 for(const vp of [{width:320,height:568},{width:390,height:664},{width:844,height:390}]){await page.setViewportSize(vp);await page.waitForTimeout(150);for(const id of ['tab-arrange','tab-collections','tab-save','edit-fit','render-mode']){await page.locator('#'+id).scrollIntoViewIfNeeded();const r=await page.locator('#'+id).boundingBox();check('reachable-'+vp.width+'-'+id,!!r&&r.x>=-1&&r.y>=-1&&r.x+r.width<=vp.width+1&&r.y+r.height<=vp.height+1);}const small=await page.locator('#inspector button:not([hidden])').evaluateAll(es=>es.filter(e=>e.getClientRects().length).filter(e=>e.getBoundingClientRect().height<44).map(e=>({id:e.id,height:e.getBoundingClientRect().height})));check('touch-targets-'+vp.width,small.length===0,small);}
 await page.setViewportSize({width:390,height:844});check('select-no-ios-zoom',await page.locator('#edit-guests').evaluate(e=>parseFloat(getComputedStyle(e).fontSize)>=16));
 await tap('tab-save');await tap('edit-save');await page.waitForFunction(()=>!busy);const saved=await state();await page.reload();await ready();await drawn();check('atomic-reload',JSON.stringify(await state())===JSON.stringify(saved)&&await page.evaluate(n=>photoBlob.size===n,file.buffer.length));
 await page.locator('#edit-guests').selectOption('2');await page.reload();await ready();await drawn();check('reload-unsaved-edits',JSON.stringify(await state())===JSON.stringify(saved),'Reload restores the last explicit save, not unsaved edits');
 for(let n=0;n<5;n++){await page.locator('#edit-guests').selectOption('2');await page.locator('#edit-guests').selectOption('4');await page.locator('#edit-guests').selectOption('6')}await drawn();check('rapid-guest-changes',await page.evaluate(()=>items.length===24&&groups.length===6&&renderer3D.stats().groups===6));
 const beforeReset=await state();await tap('reset');await drawn();check('3d-reset-clears-meshes',await page.evaluate(()=>renderer3D.stats().items===0&&!!photoBlob));await tap('undo');await drawn();check('3d-reset-undo',JSON.stringify(await state())===JSON.stringify(beforeReset));
 // Real storage failures (open/put), malformed records, and very large images.
 await page.evaluate(()=>{window.auditWrite=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(){throw new DOMException('Test quota','QuotaExceededError')}});await tap('tab-save');await tap('edit-save');await page.waitForFunction(()=>!busy);check('quota-failure',/NOT SAVED/.test(await page.locator('#storage-note').textContent()));await page.evaluate(()=>IDBObjectStore.prototype.put=window.auditWrite);
 await tap('edit-save');await page.waitForFunction(()=>!busy);const good=await state();await page.evaluate(async()=>{window.auditGood=await TableStorage.read();await TableStorage.write({...window.auditGood,scene:{version:40}})});await tap('edit-restore');await page.waitForFunction(()=>!busy);check('corrupt-record',JSON.stringify(await state())===JSON.stringify(good)&&/COULD NOT RESTORE/.test(await page.locator('#storage-note').textContent()));
 await page.evaluate(async()=>{await TableStorage.write({...window.auditGood,photo:null})});await tap('edit-restore');await page.waitForFunction(()=>!busy);check('missing-photo',JSON.stringify(await state())===JSON.stringify(good)&&/COULD NOT RESTORE/.test(await page.locator('#storage-note').textContent()));await page.evaluate(()=>TableStorage.write(window.auditGood));
 await page.locator('#photo-input').setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('broken')});await page.waitForFunction(()=>document.getElementById('status').textContent.includes('could not be opened'));check('invalid-image-retains-scene',JSON.stringify(await state())===JSON.stringify(good));
 await page.locator('#photo-input').setInputFiles({name:'oversize.jpg',mimeType:'image/jpeg',buffer:Buffer.alloc(41*1024*1024)});await page.waitForFunction(()=>document.getElementById('status').textContent.includes('too large'));check('over-40mb-rejected',JSON.stringify(await state())===JSON.stringify(good));
 const large=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=6000;c.height=4000;const d=c.getContext('2d');d.fillStyle='#ccbbaa';d.fillRect(0,0,c.width,c.height);return c.toDataURL('image/jpeg',.8).split(',')[1]});const largeStart=Date.now();await page.locator('#photo-input').setInputFiles({name:'24-megapixel.jpg',mimeType:'image/jpeg',buffer:Buffer.from(large,'base64')});await page.waitForFunction(()=>calibration===null);check('24mp-image-decodes',await page.evaluate(()=>Math.abs(sceneRatio-1.5)<.001),{elapsedMs:Date.now()-largeStart});await tap('edit-restore');await page.waitForFunction(()=>!busy);await drawn();
 // Sustained native controls: 3 minutes, collections and group transforms, real save/restore.
 await tap('expand');await tap('tab-arrange');await page.locator('.piece[aria-label^="plate"]').nth(2).tap();await tap('tool-size');
 await page.evaluate(()=>{window.auditLongTasks=[];window.auditLag=[];let previous=performance.now();window.auditLagTimer=setInterval(()=>{const now=performance.now(),lag=now-previous-50;if(lag>50)window.auditLag.push(lag);previous=now},50);window.auditLongSupported=PerformanceObserver.supportedEntryTypes?.includes('longtask')||false;if(window.auditLongSupported){window.auditObserver=new PerformanceObserver(l=>window.auditLongTasks.push(...l.getEntries().map(e=>e.duration)));window.auditObserver.observe({type:'longtask',buffered:true})}});
 const samples=[],start=Date.now();let cycles=0;while(Date.now()-start<180000){
  await page.locator('#size').press('ArrowRight');await page.locator('#size').press('ArrowLeft');
  await tap('duplicate');await tap('delete');await tap('undo');await tap('undo');
  await tap('tab-collections');await page.locator('#edit-plates').selectOption(cycles%2?'sage':'blue');await page.locator('#edit-cutlery').selectOption(cycles%2?'gold':'ink');await page.locator('#edit-glassware').selectOption(cycles%2?'amber':'rose');
  await tap('tab-save');await tap('edit-save');await page.waitForFunction(()=>!busy);await tap('edit-restore');await page.waitForFunction(()=>!busy);await tap('tab-arrange');await page.locator('.piece[aria-label^="plate"]').nth(2).tap();await drawn();
  if(cycles%4===0){samples.push(await page.evaluate(()=>({...renderer3D.stats(),domPieces:document.querySelectorAll('.piece').length,undoEntries:history.length,livePhotoURLs:window.auditURLs.size})));console.log('AUDIT stress seconds '+Math.round((Date.now()-start)/1000)+' cycles '+cycles);}cycles++;
 }
 report.performance.stress={durationMs:Date.now()-start,cycles,samples,longTasks:await page.evaluate(()=>{clearInterval(window.auditLagTimer);window.auditObserver?.disconnect();return {supported:window.auditLongSupported,durations:window.auditLongTasks,eventLoopLagOver50Ms:window.auditLag}})};
 check('stress-resource-stability',samples.every(s=>s.items===24&&s.groups===6&&s.domPieces===24&&s.undoEntries<=25&&s.livePhotoURLs===1&&s.geometries===samples[0].geometries&&s.textures<=samples[0].textures+1),samples.map(({geometries,textures,items,groups})=>({geometries,textures,items,groups})));
 report.performance.benchmark=await page.evaluate(()=>renderer3D.benchmark());check('packed-environment-accounted',report.performance.benchmark.environmentBytes>256*256*8&&report.performance.benchmark.estimatedGraphicsBytes>=report.performance.benchmark.environmentBytes+report.performance.benchmark.geometryBytes+report.performance.benchmark.shadowBytes);report.performance.loading=await page.evaluate(()=>({navigation:performance.getEntriesByType('navigation').map(n=>({domContentLoadedMs:n.domContentLoadedEventEnd,loadMs:n.loadEventEnd})),renderer:performance.getEntriesByType('resource').filter(e=>e.name.includes('dist/table3d')).map(e=>({durationMs:e.duration,transferSize:e.transferSize,decodedBytes:e.decodedBodySize}))}));
 await page.locator('#stage').screenshot({path:'test-results/audit-3d.png'});
 // Actual WebGL lose-context extension, rather than dispatching a pretend event.
 const beforeLoss=await state();const lost=await page.evaluate(()=>{const gl=document.getElementById('table-3d').getContext('webgl2'),ext=gl.getExtension('WEBGL_lose_context');if(!ext)return false;ext.loseContext();return true});if(lost)await page.waitForFunction(()=>!is3D());check('actual-context-loss',lost&&JSON.stringify(await state())===JSON.stringify(beforeLoss));
 // Storage unavailable must release startup inertness and permit editing.
 const denied=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await denied.addInitScript(()=>{Object.defineProperty(window,'indexedDB',{get(){throw new DOMException('Denied','SecurityError')}});sessionStorage.setItem('table-studio.renderer','2d')});const dp=await denied.newPage();await dp.goto(base);await dp.waitForFunction(()=>!document.querySelector('main').inert);await dp.locator('#guests-6').tap();check('idb-unavailable-editable',await dp.locator('.piece').count()===24);await dp.locator('#save').tap();await dp.waitForFunction(()=>!busy);check('idb-unavailable-message',/NOT SAVED/.test(await dp.locator('#storage-note').textContent()));await denied.close();
 const loading=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await loading.route('**/dist/table3d.js*',r=>r.abort());const lp=await loading.newPage();await lp.goto(base);await lp.waitForFunction(()=>!document.querySelector('main').inert);await lp.locator('#guests-2').tap();await lp.waitForFunction(()=>document.getElementById('render-status').dataset.mode==='2d');check('bundle-failure-editable',await lp.locator('.piece').count()===8);await loading.unroute('**/dist/table3d.js*');await lp.locator('#render-mode').tap();await lp.waitForFunction(()=>is3D());check('bundle-retry-recovers',await lp.locator('.piece').count()===8);await loading.close();
 const slowCtx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),slowPage=await slowCtx.newPage();await slowPage.goto(base);await slowPage.waitForFunction(()=>!document.querySelector('main').inert);await slowPage.locator('#guests-6').tap();await slowPage.waitForFunction(()=>is3D());const slowResult=await slowPage.evaluate(async()=>{const before=JSON.stringify(scene()),raf=window.requestAnimationFrame,caf=window.cancelAnimationFrame;window.requestAnimationFrame=cb=>setTimeout(()=>cb(performance.now()),320);window.cancelAnimationFrame=clearTimeout;let first,second;try{first=await renderer3D.benchmark();for(let n=0;n<2&&is3D();n++)second=await renderer3D.benchmark()}finally{window.requestAnimationFrame=raf;window.cancelAnimationFrame=caf}return {first,second,fallback:!is3D(),preserved:before===JSON.stringify(scene())}});check('slow-frames-counted',slowResult.first.fps!==null&&slowResult.first.fps<5,slowResult.first);check('slow-device-fallback',slowResult.fallback&&slowResult.preserved);await slowCtx.close();
 check('privacy-get-only',report.network.every(r=>r.method==='GET'&&r.bytes===0&&(r.url.startsWith(base)||r.url.startsWith('blob:')||r.url.startsWith('data:'))));check('no-uncaught-errors',report.errors.length===0,report.errors);
 }finally{fs.writeFileSync('test-results/audit.json',JSON.stringify(report,null,2));await browser.close()}
 const failed=report.checks.filter(c=>!c.pass);console.log('AUDIT RESULT '+JSON.stringify({checks:report.checks.length,failed,performance:report.performance}));if(!baseline)assert.deepEqual(failed,[]);
})().catch(e=>{console.error(e);process.exit(1)});
