// Real browser integration, using native controls and the shipped 3D renderer.
const assert=require('node:assert/strict'),fs=require('node:fs'),pw=require('playwright');
(async()=>{const browser=await pw[process.env.BROWSER||'webkit'].launch({headless:true});
 try{const base=(process.env.BASE_URL||'http://127.0.0.1:8000/').replace(/\/$/,'')+'/',context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});
 const page=await context.newPage(),errors=[],external=[];page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET'||!r.url().startsWith(base)&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))external.push(r.url());});
 const tap=id=>page.locator('#'+id).tap(),state=()=>page.evaluate(()=>structuredClone(scene())),ready=()=>page.waitForFunction(()=>!document.querySelector('main').inert),drawn=()=>page.waitForFunction(()=>document.querySelector('#table-3d').dataset.stats&&JSON.parse(document.querySelector('#table-3d').dataset.stats).items===document.querySelectorAll('.piece').length);
 await page.goto(base);await ready();
 const q=[{x:.09,y:.90},{x:.92,y:.84},{x:.73,y:.20},{x:.31,y:.23}];
 const png=await page.evaluate(q=>{const c=document.createElement('canvas');c.width=1200;c.height=800;const d=c.getContext('2d');d.fillStyle='#e2e1d9';d.fillRect(0,0,1200,800);d.beginPath();q.forEach((p,i)=>i?d.lineTo(p.x*1200,p.y*800):d.moveTo(p.x*1200,p.y*800));d.closePath();const g=d.createLinearGradient(0,180,0,730);g.addColorStop(0,'#bbaa92');g.addColorStop(1,'#d0b894');d.fillStyle=g;d.fill();d.save();d.clip();d.lineWidth=1;d.strokeStyle='#aa967855';for(let y=180;y<750;y+=34){d.beginPath();d.moveTo(0,y);d.lineTo(1200,y-50);d.stroke();}d.restore();return c.toDataURL().split(',')[1]},q);
 await page.locator('#photo-input').setInputFiles({name:'synthetic-3d-qa.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.waitForFunction(()=>['3d','2d'].includes(document.getElementById('render-status').dataset.mode));
 assert.equal(await page.locator('#render-status').getAttribute('data-mode'),'3d','WebGL2 must actually render; fallback is tested separately');
 await tap('edit-calibrate');for(let i=0;i<4;i++){const b=await page.locator('.corner').nth(i).boundingBox(),r=await page.locator('#stage').boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(r.x+q[i].x*r.width,r.y+q[i].y*r.height,{steps:8});await page.mouse.up();}await tap('calibration-done');
 for(const n of [2,4,6]){await page.locator('#edit-guests').selectOption(String(n));await drawn();const stats=JSON.parse(await page.locator('#table-3d').getAttribute('data-stats'));assert.equal(stats.items,n*4);assert.equal(stats.groups,n);assert.ok(stats.triangles>1000);}
 await tap('expand');await drawn();await page.locator('.piece[aria-label^="plate"]').nth(2).tap();assert.equal(await page.locator('.piece.selected').count(),4);
 const before=await state();await page.locator('#size').press('End');await tap('edit-fit');await drawn();const fitted=await state();assert.notDeepEqual(before.items,fitted.items);assert.equal(await page.evaluate(()=>TableFit.inside(items,fitContext())),true);
 // A true browser drag manipulates the selected 3D group through the common input path.
 const plate=page.locator('.piece.selected[aria-label^="plate"]'),r=await plate.boundingBox(),old=await state();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width/2+8,r.y+r.height/2-5,{steps:8});await page.mouse.up();await drawn();const moved=await state();assert.notDeepEqual(moved.items,old.items);
 const groupId=await page.evaluate(()=>current().groupId),dist=(a,b,ratio)=>Math.hypot(a.x-b.x,(a.y-b.y)/ratio),a=old.items.filter(i=>i.groupId===groupId),b=moved.items.filter(i=>i.groupId===groupId),ratio=await page.evaluate(()=>planeRatio());
 const factor=b[0].scale/a[0].scale;for(let j=1;j<4;j++)assert.ok(Math.abs(dist(b[0],b[j],ratio)-dist(a[0],a[j],ratio)*factor)<1e-7);
 await tap('tool-rotation');let previous=await state();await page.locator('#rotation').press('ArrowRight');assert.notDeepEqual((await state()).items,previous.items);
 await tap('duplicate');await drawn();assert.equal((await state()).items.length,28);await tap('delete');await tap('undo');await tap('undo');await drawn();assert.equal((await state()).items.length,24);
 await tap('mode-item');await tap('pick-knife');await tap('tool-size');previous=await state();await page.locator('#size').press('ArrowRight');assert.equal((await state()).items.filter((i,n)=>JSON.stringify(i)!==JSON.stringify(previous.items[n])).length,1);await tap('mode-setting');
 await tap('tab-collections');for(const [category,value] of [['plates','sage'],['cutlery','gold'],['glassware','amber']]){previous=await state();await page.locator('#edit-'+category).selectOption(value);assert.deepEqual((await state()).items.map(({collection,...i})=>i),previous.items.map(({collection,...i})=>i));}
 await tap('tab-save');await tap('edit-save');await page.waitForFunction(()=>document.getElementById('save-indicator').dataset.state==='saved');const saved=await state();await page.reload();await ready();await drawn();assert.deepEqual(await state(),saved);assert.match(await page.locator('#table-photo').getAttribute('src'),/^blob:/);
 await tap('expand');await tap('edit-fit');await drawn();await tap('tab-save');await page.locator('#performance summary').tap();await tap('perf-start');await page.waitForFunction(()=>!!document.getElementById('perf-output').dataset.result);const perf=JSON.parse(await page.locator('#perf-output').getAttribute('data-result'));assert.ok(perf.measuredFrames>10);assert.ok(perf.geometryBytes<500000);assert.ok(perf.textures<15);console.log('3D PERFORMANCE '+base+' '+JSON.stringify(perf));fs.writeFileSync('test-results/performance-3d.json',JSON.stringify(perf,null,2));
 await tap('tab-arrange');await page.locator('#stage').screenshot({path:'test-results/comparison-3d.png'});const comparison=await state();await tap('render-mode');assert.equal(await page.locator('#table-3d').isVisible(),false);assert.deepEqual(await state(),comparison);await page.locator('#stage').screenshot({path:'test-results/comparison-2d.png'});await tap('render-mode');await drawn();assert.deepEqual(await state(),comparison);
 for(const quad of [[{x:.39,y:.95},{x:.64,y:.92},{x:.6,y:.1},{x:.44,y:.12}],[{x:.03,y:.69},{x:.97,y:.69},{x:.9,y:.4},{x:.1,y:.4}]]){await tap('edit-calibrate');await page.evaluate(q=>{calibrationDraft=q;paint()},quad);await tap('calibration-done');await page.locator('#edit-guests').selectOption('2');await page.locator('#edit-guests').selectOption('6');await tap('edit-fit');await drawn();assert.equal(await page.evaluate(()=>TableFit.inside(items,fitContext())),true);}
 // Hardware context loss cannot erase the arrangement or block existing controls.
 const preserved=await state();await page.evaluate(()=>document.getElementById('table-3d').dispatchEvent(new Event('webglcontextlost',{cancelable:true})));assert.equal(await page.locator('#render-status').getAttribute('data-mode'),'2d');assert.deepEqual(await state(),preserved);await page.locator('.piece[aria-label^="plate"]').first().tap();await tap('tool-size');await page.locator('#size').press('ArrowRight');assert.notDeepEqual((await state()).items,preserved.items);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 const blocked=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await blocked.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/.test(type)?null:get.call(this,type,...args);};});const noGL=await blocked.newPage();await noGL.goto(base);await noGL.waitForFunction(()=>!document.querySelector('main').inert);await noGL.locator('#guests-6').tap();await noGL.waitForFunction(()=>document.getElementById('render-status').dataset.mode==='2d');assert.equal(await noGL.locator('.piece').count(),24);await blocked.close();
 console.log('PASS 3D '+base+': native calibration; 2/4/6 real meshes; group drag/rotation/scale; Fit; single edits; collections; persistence; comparison; narrow/wide; WebGL failure/context loss fallback; local privacy.');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
